-- MySQL Script generated by MySQL Workbench
-- Sun Oct  3 09:36:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Drop tables
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categoria` ;
DROP TABLE IF EXISTS `Credencial` ;
DROP TABLE IF EXISTS `Usuario` ;

-- -----------------------------------------------------
-- Schema whip
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `whip` ;
CREATE SCHEMA IF NOT EXISTS `whip` DEFAULT CHARACTER SET utf8 ;
USE `whip` ;

-- -----------------------------------------------------
-- Table `Categoria`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Categoria` (
  `Sigla` CHAR(10) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(30) NULL,
  `Observacao` MEDIUMTEXT NULL,
  `FK_Usuario_Username` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Categoria_Usuario1`
    FOREIGN KEY (`FK_Usuario_Username`)
    REFERENCES `Usuario` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Credencial`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Credencial` (
  `Username` VARCHAR(30) NOT NULL,
  `Site` VARCHAR(100) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `DataCriacao` DATE NOT NULL,
  `Observacao` MEDIUMTEXT NULL,
  `FK_Usuario_Username` VARCHAR(30) NOT NULL,
  `FK_Categoria_Sigla` CHAR(10) NOT NULL,
  PRIMARY KEY (`Username`, `Site`),
  CONSTRAINT `fk_Credencial_Usuario`
    FOREIGN KEY (`FK_Usuario_Username`)
    REFERENCES `Usuario` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Credencial_Categoria1`
    FOREIGN KEY (`FK_Categoria_Sigla`)
    REFERENCES `Categoria` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Usuario` (
  `Username` VARCHAR(30) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Create indexes
-- -----------------------------------------------------
CREATE INDEX `fk_Categoria_Usuario1_idx` ON `Categoria` (`FK_Usuario_Username` ASC) VISIBLE;

CREATE INDEX `fk_Credencial_Usuario_idx` ON `Credencial` (`FK_Usuario_Username` ASC) VISIBLE;

CREATE INDEX `fk_Credencial_Categoria1_idx` ON `Credencial` (`FK_Categoria_Sigla` ASC) VISIBLE;

CREATE UNIQUE INDEX `Username_UNIQUE` ON `Usuario` (`Username` ASC) VISIBLE;

CREATE UNIQUE INDEX `Email_UNIQUE` ON `Usuario` (`Email` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
